# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMk7Qtuzbl-ACXnmUQH3AZS-VR-l0Z_D
"""

import numpy as np
import math
sum1=0
sum2=0
print(" Welcome to crcket match")
n=int(input("Enter no. of overs to play the match"))
b=n*6
print(" Start playing team A for ",b," balls")
for i in range(1,b+1):
  ch=input(" \n to play, press p  ")
  if(ch=='p'):
    r1=np.random.randint(1,7,1)
    if(r1!=5):
      print("\n \n \n ball no. ",i,"\n This ball: ",r1)
      sum1=sum1+r1
      print(" Score: ",sum1)
      rr=(sum1/i)*6
      p=rr*n
      print("Current run rate: ",rr)
      print("Projected score: ",p)
    else:
      print("ball no. ",i)
      print("Dot ball")
      r1=0
      print("This Ball: ",r1)
      print(" Score: ",sum1)
      rr=(sum1/i)*6
      p=math.ceil(rr*n)
      print("Current run rate: ",rr)
      print("Projected score: ",p)
    if(i%6==0):
     o=i//6
     print(" After ",o," over \n Score: ",sum1)
 
print("\n \n \nTotal Score TEAM A:: ",sum1)
print("Team B: Target: ",sum1+1)
 
print("Team B require ",sum1+1," runs to win")
rq=(sum1+1)/n
print("Required Run rate to win:",rq)
 
print("  \n\n Batting for team B")
i=1
while(sum2<=sum1 and i<=b):
  ch=input(" \n to play, press p  ")
  if(ch=='p'):
    r2=np.random.randint(1,7,1)
    if(r2!=5):
      print("\n \n \n ball no. ",i,"\n This ball: ",r2)
      sum2=sum2+r2
      print(" Score: ",sum2)
      rr=(sum2/i)*6
      p=rr*n
      print("Current run rate: ",rr)
      rq=sum1-sum2+1
      print(" Requre ",rq," runs more to win from",b-i," balls")
      rrq=(rq/(b-i))*6
      print("Required rate: ",rrq)
    else:
      print("ball no. ",i)
      print("Dot ball")
      r2=0
      print("This Ball: ",r2)
      print(" Score: ",sum2)
      rr=(sum2/i)*6
      p=rr*n
      print("Current run rate: ",rr)
      rq=sum1-sum2+1
      print(" Requre ",rq," runs more to win from ",b-i," balls")
      rrq=(rq/(b-i))*6
      print("Required rate: ",rrq)
      
    if(i%6==0):
     o=i//6
     print(" After ",o," over \n Score: ",sum2)
  i=i+1  
print("\n \n \nTotal Score TEAM B :: ",sum2)
 
if(sum1>sum2):
  print("A won by ",sum1-sum2," runs")
elif(sum1<sum2):
  print("Team B beat Team A")
else:
  print(" Match is tied")